title: Driver Induction
description: Grats on driver. You are now officially room staff of Other Metas. There are a few more rules that you need to know, but are still expected to follow ALL voice rules. (If you need to review just do /staffintro).
google_analytics: 
show_downloads: true
theme: jekyll-theme-midnight

gems:
  - jekyll-mentions
